create extension if not exists pgcrypto;

create table if not exists campanhas (
  id bigint generated by default as identity primary key,
  titulo text not null,
  data_retirada date not null,
  prazo_final_pedidos timestamptz not null,
  mensagem_cliente text default '',
  observacoes_internas text default '',
  status text not null default 'rascunho' check (status in ('rascunho', 'aberta', 'encerrada_automaticamente', 'encerrada_manualmente', 'finalizada')),
  encerrada_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists produtos_campanha (
  id bigint generated by default as identity primary key,
  campanha_id bigint not null references campanhas(id) on delete cascade,
  nome text not null,
  descricao text default '',
  preco_unitario numeric(12,2) not null default 0,
  quantidade_maxima integer not null default 0 check (quantidade_maxima >= 0),
  ativo boolean not null default true,
  ordem_exibicao integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  numero_pedido text not null unique,
  campanha_id bigint not null references campanhas(id) on delete cascade,
  nome_cliente text not null,
  telefone_cliente text not null,
  telefone_normalizado text not null,
  status text not null default 'aguardando_retirada' check (status in ('aguardando_retirada', 'retirado_pago', 'cancelado')),
  valor_total numeric(12,2) not null default 0,
  cancelado_em timestamptz,
  motivo_cancelamento text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists itens_pedido (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos(id) on delete cascade,
  produto_campanha_id bigint not null references produtos_campanha(id),
  nome_produto_snapshot text not null,
  preco_unitario_snapshot numeric(12,2) not null,
  quantidade integer not null check (quantidade > 0),
  subtotal numeric(12,2) not null,
  created_at timestamptz not null default now()
);

create unique index if not exists pedidos_telefone_ativo_idx
  on pedidos (campanha_id, telefone_normalizado)
  where status <> 'cancelado';

create or replace view produtos_campanha_resumo as
select
  p.*,
  coalesce(sum(i.quantidade) filter (where ped.status <> 'cancelado'), 0)::integer as quantidade_vendida,
  greatest(p.quantidade_maxima - coalesce(sum(i.quantidade) filter (where ped.status <> 'cancelado'), 0)::integer, 0) as quantidade_disponivel
from produtos_campanha p
left join itens_pedido i on i.produto_campanha_id = p.id
left join pedidos ped on ped.id = i.pedido_id
group by p.id;

create or replace function atualizar_campanhas_encerradas()
returns void
language sql
security definer
as $$
  update campanhas
  set status = 'encerrada_automaticamente',
      encerrada_em = now(),
      updated_at = now()
  where status = 'aberta'
    and prazo_final_pedidos <= now();
$$;

create or replace function pedido_por_telefone(p_campanha_id bigint, p_telefone text)
returns table (
  id bigint,
  numero_pedido text,
  nome_cliente text,
  telefone_cliente text,
  status text,
  valor_total numeric,
  itens jsonb
)
language sql
security definer
as $$
  select
    ped.id,
    ped.numero_pedido,
    ped.nome_cliente,
    ped.telefone_cliente,
    ped.status,
    ped.valor_total,
    coalesce(jsonb_agg(jsonb_build_object(
      'produto', i.nome_produto_snapshot,
      'quantidade', i.quantidade,
      'preco', i.preco_unitario_snapshot,
      'subtotal', i.subtotal
    ) order by i.id), '[]'::jsonb) as itens
  from pedidos ped
  left join itens_pedido i on i.pedido_id = ped.id
  where ped.campanha_id = p_campanha_id
    and ped.telefone_normalizado = regexp_replace(coalesce(p_telefone, ''), '[^0-9]', '', 'g')
    and ped.status <> 'cancelado'
  group by ped.id
  limit 1;
$$;

create or replace function criar_pedido(
  p_campanha_id bigint,
  p_nome_cliente text,
  p_telefone_cliente text,
  p_itens jsonb,
  p_substituir_pedido_id bigint default null
)
returns jsonb
language plpgsql
security definer
as $$
declare
  v_campanha campanhas%rowtype;
  v_telefone text := regexp_replace(coalesce(p_telefone_cliente, ''), '[^0-9]', '', 'g');
  v_item jsonb;
  v_produto produtos_campanha%rowtype;
  v_disponivel integer;
  v_total numeric(12,2) := 0;
  v_pedido_id bigint;
  v_numero text;
  v_existente pedidos%rowtype;
begin
  perform atualizar_campanhas_encerradas();

  select * into v_campanha from campanhas where id = p_campanha_id;
  if not found then
    return jsonb_build_object('ok', false, 'code', 'campanha_nao_encontrada', 'message', 'Campanha nao encontrada.');
  end if;

  if v_campanha.status <> 'aberta' or v_campanha.prazo_final_pedidos <= now() then
    return jsonb_build_object('ok', false, 'code', 'campanha_encerrada', 'message', 'Os pedidos desta campanha estao encerrados.');
  end if;

  if length(trim(coalesce(p_nome_cliente, ''))) < 3 then
    return jsonb_build_object('ok', false, 'code', 'nome_invalido', 'message', 'Informe o nome completo.');
  end if;

  if length(v_telefone) < 10 then
    return jsonb_build_object('ok', false, 'code', 'telefone_invalido', 'message', 'Informe um telefone valido.');
  end if;

  select * into v_existente
  from pedidos
  where campanha_id = p_campanha_id
    and telefone_normalizado = v_telefone
    and status <> 'cancelado'
  limit 1;

  if found and p_substituir_pedido_id is null then
    return jsonb_build_object('ok', false, 'code', 'pedido_duplicado', 'message', 'Ja existe um pedido para este telefone.', 'pedido_id', v_existente.id);
  end if;

  if p_substituir_pedido_id is not null then
    update pedidos
    set status = 'cancelado',
        cancelado_em = now(),
        motivo_cancelamento = 'substituido_pelo_cliente',
        updated_at = now()
    where id = p_substituir_pedido_id
      and campanha_id = p_campanha_id
      and telefone_normalizado = v_telefone
      and status <> 'cancelado';

    if not found then
      return jsonb_build_object('ok', false, 'code', 'pedido_substituicao_invalido', 'message', 'Pedido anterior nao encontrado.');
    end if;
  end if;

  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens) = 0 then
    return jsonb_build_object('ok', false, 'code', 'sem_itens', 'message', 'Escolha pelo menos um produto.');
  end if;

  for v_item in select * from jsonb_array_elements(p_itens)
  loop
    select * into v_produto
    from produtos_campanha
    where id = (v_item->>'produto_id')::bigint
      and campanha_id = p_campanha_id
      and ativo = true
    for update;

    if not found then
      return jsonb_build_object('ok', false, 'code', 'produto_indisponivel', 'message', 'Um produto selecionado nao esta disponivel.');
    end if;

    if (v_item->>'quantidade')::integer <= 0 then
      return jsonb_build_object('ok', false, 'code', 'quantidade_invalida', 'message', 'Quantidade invalida.');
    end if;

    select quantidade_disponivel into v_disponivel
    from produtos_campanha_resumo
    where id = v_produto.id;

    if (v_item->>'quantidade')::integer > v_disponivel then
      return jsonb_build_object('ok', false, 'code', 'estoque_insuficiente', 'message', 'Saldo insuficiente para ' || v_produto.nome || '. Disponivel: ' || v_disponivel || '.');
    end if;

    v_total := v_total + (v_produto.preco_unitario * (v_item->>'quantidade')::integer);
  end loop;

  insert into pedidos (numero_pedido, campanha_id, nome_cliente, telefone_cliente, telefone_normalizado, valor_total)
  values ('temp', p_campanha_id, trim(p_nome_cliente), p_telefone_cliente, v_telefone, v_total)
  returning id into v_pedido_id;

  v_numero := lpad(v_pedido_id::text, 4, '0');
  update pedidos set numero_pedido = v_numero where id = v_pedido_id;

  for v_item in select * from jsonb_array_elements(p_itens)
  loop
    select * into v_produto from produtos_campanha where id = (v_item->>'produto_id')::bigint;
    insert into itens_pedido (
      pedido_id,
      produto_campanha_id,
      nome_produto_snapshot,
      preco_unitario_snapshot,
      quantidade,
      subtotal
    )
    values (
      v_pedido_id,
      v_produto.id,
      v_produto.nome,
      v_produto.preco_unitario,
      (v_item->>'quantidade')::integer,
      v_produto.preco_unitario * (v_item->>'quantidade')::integer
    );
  end loop;

  return jsonb_build_object('ok', true, 'pedido_id', v_pedido_id, 'numero_pedido', v_numero, 'valor_total', v_total);
end;
$$;

alter table campanhas enable row level security;
alter table produtos_campanha enable row level security;
alter table pedidos enable row level security;
alter table itens_pedido enable row level security;

drop policy if exists "public_read_campaigns" on campanhas;
create policy "public_read_campaigns" on campanhas for select to anon, authenticated using (true);

drop policy if exists "auth_manage_campaigns" on campanhas;
create policy "auth_manage_campaigns" on campanhas for all to authenticated using (true) with check (true);

drop policy if exists "public_read_products" on produtos_campanha;
create policy "public_read_products" on produtos_campanha for select to anon, authenticated using (true);

drop policy if exists "auth_manage_products" on produtos_campanha;
create policy "auth_manage_products" on produtos_campanha for all to authenticated using (true) with check (true);

drop policy if exists "auth_read_orders" on pedidos;
create policy "auth_read_orders" on pedidos for select to authenticated using (true);

drop policy if exists "auth_update_orders" on pedidos;
create policy "auth_update_orders" on pedidos for update to authenticated using (true) with check (true);

drop policy if exists "auth_read_items" on itens_pedido;
create policy "auth_read_items" on itens_pedido for select to authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select on campanhas, produtos_campanha, produtos_campanha_resumo to anon, authenticated;
grant select, insert, update, delete on campanhas, produtos_campanha, pedidos, itens_pedido to authenticated;
grant execute on function atualizar_campanhas_encerradas() to anon, authenticated;
grant execute on function pedido_por_telefone(bigint, text) to anon, authenticated;
grant execute on function criar_pedido(bigint, text, text, jsonb, bigint) to anon, authenticated;

insert into campanhas (titulo, data_retirada, prazo_final_pedidos, mensagem_cliente, status)
values (
  'Venda de Paes - Quarta-feira',
  current_date + 7,
  ((current_date + 6)::text || ' 18:00:00-03')::timestamptz,
  'Retirada na Paroquia Santa Terezinha. Pagamento no momento da retirada.',
  'aberta'
)
on conflict do nothing;

insert into produtos_campanha (campanha_id, nome, descricao, preco_unitario, quantidade_maxima, ordem_exibicao)
select c.id, 'Pao italiano', 'Unidade grande', 18, 30, 1 from campanhas c where c.titulo = 'Venda de Paes - Quarta-feira'
union all
select c.id, 'Pao integral', 'Unidade', 15, 20, 2 from campanhas c where c.titulo = 'Venda de Paes - Quarta-feira'
union all
select c.id, 'Pao de queijo', 'Pacote', 12, 40, 3 from campanhas c where c.titulo = 'Venda de Paes - Quarta-feira';
